### ISSUE TITLE
Implementation details of Baselines

### ISSUE THREAD

**Issue by usamasadiq706** [axelBarroso/Key.Net#9]
I hope you are doing well.
Actually, I am working on reproducing the matching score table in your paper. I want to know about the details of the source codes or implementations details of baselines models against which you compare your Key.Net. 
Any help will be appreciated.
Thanks a lot.

**Comment by axelBarroso** [comment]
Hello, 

The matching score table was done with an old version of Key.Net and a TensorFlow implementation of HardNet. The TensorFlow implementation of HardNet turned out to perform poorly compared with the official Pytorch one. You should get higher results than those in the table with the provided implementation. About the details of the source codes, in our experiment, we took directly authors implementations and substitute their descriptors by our HardNet-TF network. 

I saw that you are coding Key.Net-PyTorch, that is exciting! I will be using it! You can check the performance of your implementation in our benchmark and see how it performs compared to our TF model. 

Best of luck!

**Comment by usamasadiq706** [comment]
Hi, 
Thank you for your response. I am aware of the issue of performance degradation of matching score due to use of TensorFlow's implementation of HardNet. I am using the official PyTorch implementation of HardNet. 

Secondly, I am thankful to you for sharing the information about the details of the implementation of baseline models. This will help me a lot.

At last, I appreciate your interest in my Pytorch implementation of Key.Net. I will share code and all results as soon as possible. I am using Pytorch implementation of HardNet to evaluate my implementation. 

One thing, could you please explain which "benchmark" are you referring for evaluation?

Thanks.

**Comment by axelBarroso** [comment]
Hello,

The benchmark I was referring is the one provided in the Github (https://github.com/axelBarroso/Key.Net/blob/master/hsequeces_bench.py). There you can compute the matching score as well as the repeatability of your method. Hope it helps!
